services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik=true
      - traefik.http.routers.traefik.rule=Host("traefik.docker.localhost")
      - traefik.http.routers.traefik.service=api@internal
    ports:
      # HTTPS / SSL port
      - "443:443"
      - "80:80"
      # The Traefik Web UI port (enabled by api:insecure)
      - "8899:8080"
    environment:
      - TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=false
      - TRAEFIK_API_DASHBOARD=true
      - TRAEFIK_API_INSECURE=true
      - TRAEFIK_PROVIDERS_DOCKER=true
      - TRAEFIK_LOG_FORMAT=common
      - TRAEFIK_ENTRYPOINTS_http_ADDRESS=:80
      - TRAEFIK_ENTRYPOINTS_http_HTTP_REDIRECTIONS_ENTRYPOINT_TO=https
      - TRAEFIK_ENTRYPOINTS_http_HTTP_REDIRECTIONS_ENTRYPOINT_SCHEME=https
      - TRAEFIK_ENTRYPOINTS_https_ADDRESS=:443
      #- TRAEFIK_LOG_LEVEL=DEBUG
      #- TRAEFIK_ACCESSLOG=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      main:
  ldap:
    extends:
        file: ./dms-ad-openldap/docker-compose.yml
        service: openldap
    networks:
        main:
          aliases:
            - openldap
  keycloak:
    extends:
        file: ./dms-ad-openldap/docker-compose.yml
        service: keycloak
    networks:
      main:
        aliases:
          - keycloak
  phpldapadmin:
    extends:
      file: ./dms-ad-openldap/docker-compose.yml
      service: phpldapadmin
    networks:
      main:
        aliases:
          - phpldapadmin
    links:
      - ldap
  mail:
    image: mailhog/mailhog
    restart: always
    ports:
      - 8025:8025
    networks:
      main:
        aliases:
          - mail
  db:
    image: mariadb:latest
    ports:
      - "53306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'cakephp'
      MYSQL_DATABASE: 'dms-calendar'
      MYSQL_USER: 'calendar'
      MYSQL_PASSWORD: 'calendar'
    networks:
      main:
        aliases:
          - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=cakephp
    links:
      - db
    ports:
      - 8081:80
    volumes:
      - /sessions
    networks:
      main:
        aliases:
          - phpmyadmin
  app:
    build:
      context: .
      target: develop
      args:
        FWATCHDOG_VERSION: "0.7.1"
    volumes:
      - ./vendor:/var/www/vendor:rw
      - ./logs/www:/var/www/logs:rw
      - ./logs/var:/var/log/:rw
      - .:/var/www:rw
    links:
      - db
    ports:
      - "8000:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - traefik.enable=true
      - traefik.http.routers.app.tls=true
      - traefik.http.routers.app.rule=Host("calendar.docker.localhost")
    entrypoint: ['/var/www/.docker/wait-for-it.sh', "db:3306", "-s", "-t", "120", "--" ]
    command: '/var/www/.docker/startup.sh'
    environment:
      DEBUG: true
      DB_HOST: 'db' # Leave this as 'db' to utilize MySQL container(s)
      DB_USERNAME: 'calendar'
      DB_PASSWORD: 'calendar'
      DB_DATABASE: 'dms-calendar'
      DB_SEED: 'DatabaseSeed'
      EMAIL_HOST: 'mail'
      EMAIL_PORT: 1025
      EMAIL_TIMEOUT: 30
      EMAIL_TLS: false
      AD_SERVER: 'openldap'
      AD_BASE: 'dc=dms,dc=local'
      AD_SUFFIX: '@dms.local'
      AD_BIND_UN: 'cn=admin,dc=dms,dc=local'
      AD_BIND_PW: 'Adm1n!'
      AD_USE_TLS: true
    networks:
        main:
            aliases:
                - app
networks:
    main:
