services:
    ldap:
        extends:
            file: ./dms-ad-openldap/docker-compose.yml
            service: openldap
        networks:
            main:
                aliases:
                    - openldap
    phpldapadmin:
        extends:
            file: ./dms-ad-openldap/docker-compose.yml
            service: phpldapadmin
        networks:
            main:
                aliases:
                    - phpldapadmin
        links:
        - ldap
    mail:
      image: mailhog/mailhog
      restart: always
      ports:
        - 8025:8025
    db:
        image: mariadb:latest
        ports:
            - "53306:3306"
        environment:
          MYSQL_ROOT_PASSWORD: 'cakephp'
          MYSQL_DATABASE: 'dms-calendar'
          MYSQL_USER: 'calendar'
          MYSQL_PASSWORD: 'calendar'
        networks:
            main:
                aliases:
                    - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=cakephp
        links:
            - db
        ports:
            - 8081:80
        volumes:
            - /sessions
        networks:
          main:
              aliases:
                  - phpmyadmin
    app:
        build:
          context: .
          args:
            FWATCHDOG_VERSION: "0.7.1"
        volumes:
            - vendor:/var/www/vendor
            - logs:/var/www/logs
            - .:/var/www
        links:
            - db
        ports:
            - "8080:80"
        entrypoint: ['/var/www/.docker/wait-for-it.sh', "db:3306", "-s", "-t", "120", "--" ]
        command: '/var/www/.docker/startup.sh'
        environment:
          DEBUG: true
          DB_HOST: 'db' # Leave this as 'db' to utilize MySQL container(s)
          DB_USERNAME: 'calendar'
          DB_PASSWORD: 'calendar'
          DB_DATABASE: 'dms-calendar'
          DB_SEED: 'DatabaseSeed'
          EMAIL_HOST: 'email'
          EMAIL_PORT: 1025
          EMAIL_TIMEOUT: 30
          EMAIL_TLS: false
          AD_SERVER: 'openldap'
          AD_BASE: 'dc=dms,dc=local'
          AD_SUFFIX: '@dms.local'
          AD_BIND_UN: 'cn=admin,dc=dms,dc=local'
          AD_BIND_PW: 'Adm1n!'

        networks:
            main:
                aliases:
                    - app
networks:
    main:
volumes:
    vendor:
    logs:
