name: Build and Release Container Image

on:
  pull_request_target:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      USERNAME: '<SOMETHING>'
      IMG_NAME: '<SOME_IMG>'
    steps:
      - uses: actions/checkout@v2

      - name: Set App Name
        run: 'echo "IMG_NAME=$(echo ${USERNAME})/$(echo ${IMG_NAME})" >> $GITHUB_ENV'

      - name: login to dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ env.USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build image
        uses: dfreilich/pack-action@v2
        with:
          args: 'build ${{ env.IMG_NAME }} --builder paketobuildpacks/builder:base  --publish'
